namespace: crytectobi
name: unifi_controller_facts
version: 1.0.0
description: Module to access data of local Unifi Controller facts.
repository: https://github.com/crytectobi/unifi_controller/
readme: README.md
authors:
    - "Ken Moini"
license:
    - "GPL-3.0-only"
tags:
    - unifi
    - ubiquiti
